version: 2
jobs:
  build:
    branches:
      only:
        - source
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # - run: git config --global user.email "wanzhi09@gmail.com"
      # - run: git config --global user.name "0x11"
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn config list
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: node_modules/hexo-cli/bin/hexo deploy --generate
